# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    branch: refs/heads/main
    commit: ccecc2b323abc203af4763134099e12fbe88779a
    createdBy: lhumke
    deployTimestamp: "1653758935680"
    deployment.kubernetes.io/revision: "3"
    jobName: deploy_backend
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":"2022-05-09T09:53:14Z","labels":{"k8s-app":"portal-backend"},"managedFields":[{"apiVersion$
    provider: GitHub
    repository: Smart-City-SoSe-2022/Portal
    run: "2401724205"
    runUri: https://github.com/Smart-City-SoSe-2022/Portal/actions/runs/2401724205
    workflow: Docker
  generation: 7
  labels:
    k8s-app: portal-backend
  name: portal-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: portal-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: portal-backend
      name: portal-backend
    spec:
      volumes:
        - name: env
          configMap:
            name: portal-config
            items: 
              - key: env
                path: .env
      containers:
      - image: ghcr.io/smart-city-sose-2022/portal-backend:58153f6f77130c5b77e3f36d6fdb722cac2fbad9
        imagePullPolicy: Always
        name: portal-backend
        volumeMounts:
          - name: env
            readOnly: true
            mountPath: /app/.env
            subPath: .env
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-05-09T10:34:48Z"
    lastUpdateTime: "2022-05-09T10:34:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-09T09:53:14Z"
    lastUpdateTime: "2022-05-28T17:11:57Z"
    message: ReplicaSet "portal-backend-6dd5999646" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
